//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManagement.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessManagement.Resources.LanguageResources.BlogResource", typeof(BlogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        public static string Bilder {
            get {
                return ResourceManager.GetString("Bilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Picture.
        /// </summary>
        public static string CovPic {
            get {
                return ResourceManager.GetString("CovPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed &quot;Cover Pic&quot; is required!.
        /// </summary>
        public static string CovPicReq {
            get {
                return ResourceManager.GetString("CovPicReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Video Youtube link.
        /// </summary>
        public static string CovVidLink {
            get {
                return ResourceManager.GetString("CovVidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Cover Video&quot; is requiered!.
        /// </summary>
        public static string CovVidReq {
            get {
                return ResourceManager.GetString("CovVidReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deac {
            get {
                return ResourceManager.GetString("Deac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating a post.
        /// </summary>
        public static string DeactPost {
            get {
                return ResourceManager.GetString("DeactPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to deactivate a post.
        /// </summary>
        public static string DeactPostQuestion {
            get {
                return ResourceManager.GetString("DeactPostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a post.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please try again..
        /// </summary>
        public static string ErrOcc {
            get {
                return ResourceManager.GetString("ErrOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file types: .jpg, .bmp, .png, .jpeg.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text:.
        /// </summary>
        public static string FullTxt {
            get {
                return ResourceManager.GetString("FullTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Full text&quot; is required.
        /// </summary>
        public static string FullTxtReq {
            get {
                return ResourceManager.GetString("FullTxtReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline:.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feild &quot;Headline&quot; is required.
        /// </summary>
        public static string HeadlineReq {
            get {
                return ResourceManager.GetString("HeadlineReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Marketing.
        /// </summary>
        public static string MailM {
            get {
                return ResourceManager.GetString("MailM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information, more success.
        /// </summary>
        public static string MorInfoMorSuccess {
            get {
                return ResourceManager.GetString("MorInfoMorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new post.
        /// </summary>
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product.
        /// </summary>
        public static string NoProduct {
            get {
                return ResourceManager.GetString("NoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results!.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected....
        /// </summary>
        public static string NotSelect {
            get {
                return ResourceManager.GetString("NotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other posts.
        /// </summary>
        public static string OtherPosts {
            get {
                return ResourceManager.GetString("OtherPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a picture from the allowed file types.
        /// </summary>
        public static string PicTypeSel {
            get {
                return ResourceManager.GetString("PicTypeSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Product&quot; is required.
        /// </summary>
        public static string ProductReq {
            get {
                return ResourceManager.GetString("ProductReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date:.
        /// </summary>
        public static string PubDate {
            get {
                return ResourceManager.GetString("PubDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Publication date&quot; is required.
        /// </summary>
        public static string PubDateReq {
            get {
                return ResourceManager.GetString("PubDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected picture.
        /// </summary>
        public static string RemovePic {
            get {
                return ResourceManager.GetString("RemovePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text.
        /// </summary>
        public static string SearchTxt {
            get {
                return ResourceManager.GetString("SearchTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short text:.
        /// </summary>
        public static string ShortTxt {
            get {
                return ResourceManager.GetString("ShortTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Short text&quot; is required.
        /// </summary>
        public static string ShortTxtReq {
            get {
                return ResourceManager.GetString("ShortTxtReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar posts.
        /// </summary>
        public static string SimilarPosts {
            get {
                return ResourceManager.GetString("SimilarPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Marketing.
        /// </summary>
        public static string SMSM {
            get {
                return ResourceManager.GetString("SMSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Status&quot; is required.
        /// </summary>
        public static string StatusReq {
            get {
                return ResourceManager.GetString("StatusReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name:.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Tag&quot; is required.
        /// </summary>
        public static string TagReq {
            get {
                return ResourceManager.GetString("TagReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag search.
        /// </summary>
        public static string TagSearch {
            get {
                return ResourceManager.GetString("TagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 tag should be selected.
        /// </summary>
        public static string TagSelectReq {
            get {
                return ResourceManager.GetString("TagSelectReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text appears in the list with all posts.
        /// </summary>
        public static string TxtListPost {
            get {
                return ResourceManager.GetString("TxtListPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text appears when a post is opened.
        /// </summary>
        public static string TxtPostOpen {
            get {
                return ResourceManager.GetString("TxtPostOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible in time.
        /// </summary>
        public static string VisibleInTime {
            get {
                return ResourceManager.GetString("VisibleInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible now.
        /// </summary>
        public static string VisibleNow {
            get {
                return ResourceManager.GetString("VisibleNow", resourceCulture);
            }
        }
    }
}
