//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManagement.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeIndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeIndexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessManagement.Resources.LanguageResources.HomeIndexResource", typeof(HomeIndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYSIS.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATE YOUR MARKETING.
        /// </summary>
        public static string AutoMarketing {
            get {
                return ResourceManager.GetString("AutoMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND BETTER EMAIL.
        /// </summary>
        public static string BetterEmail {
            get {
                return ResourceManager.GetString("BetterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMING SOON FEATURE.
        /// </summary>
        public static string ComingFeature {
            get {
                return ResourceManager.GetString("ComingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROFESSIONAL LETTERS.
        /// </summary>
        public static string CreateProLetters {
            get {
                return ResourceManager.GetString("CreateProLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE INFORMED ABOUT OUR PROGRESS.
        /// </summary>
        public static string InformedProgress {
            get {
                return ResourceManager.GetString("InformedProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE FROM HYDRA.
        /// </summary>
        public static string MoreFromHydra {
            get {
                return ResourceManager.GetString("MoreFromHydra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIBE FOR OUR NEWSLETTER.
        /// </summary>
        public static string SubscribeNewsletter {
            get {
                return ResourceManager.GetString("SubscribeNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take advantage of our statistics page that will give you detailed reports on open, delivery, click-through and other types of mail marketing rates..
        /// </summary>
        public static string TextAnalysis {
            get {
                return ResourceManager.GetString("TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize you campaigns automatically based on interests, behavior or other gathered information about your target groups. Enjoy easy, user-friendly interface to configure your automation and be able to build more complex marketing strategies with our services..
        /// </summary>
        public static string TextAutoMarketing {
            get {
                return ResourceManager.GetString("TextAutoMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and reliable delivery of your mails across the world. We guarantee a delivery rate of 80 mails per second to the mailboxes of your customer lists on affordable prices. We have packages suitable for all types of businesses i.e. big, small and even startups!.
        /// </summary>
        public static string TextBetterEmail {
            get {
                return ResourceManager.GetString("TextBetterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration with Facebook to optimize a campaign for newsletter subscriptions and leads. You do not have a solid customer’s list or leads, yet? Build a list of newsletter subscribers and/or leads that will receive your marketing letters using the Facebook ads platform..
        /// </summary>
        public static string TextComingFeature {
            get {
                return ResourceManager.GetString("TextComingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a letter builder to create professional letters with beautiful custom design. Save custom designs or choose from a list of some default templates, which can be customized as well. Each and every design is compatible with the most popular mail clients..
        /// </summary>
        public static string TextCreateProLetters {
            get {
                return ResourceManager.GetString("TextCreateProLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon more functional modules from hydra to help your business grow. We are considering to develop modules in departments such as management, sales and marketing so that we can ease your business operations and you customers as well..
        /// </summary>
        public static string TextMoreFromHydra {
            get {
                return ResourceManager.GetString("TextMoreFromHydra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The platform is easy to use and accessible so that you can experience it firsthand. We prepared especially for you one-time-purchase and flexible packages that will allow you to experience our service without any long-term subscription bindings or any other long-term obligations at all..
        /// </summary>
        public static string TextUserFriendlyAccessible {
            get {
                return ResourceManager.GetString("TextUserFriendlyAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER FRIENDLY AND ACCESSIBLE.
        /// </summary>
        public static string UserFriendlyAccessible {
            get {
                return ResourceManager.GetString("UserFriendlyAccessible", resourceCulture);
            }
        }
    }
}
